CREATE DATABASE IF NOT EXISTS demo_his
    DEFAULT CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS demo_lis
    DEFAULT CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS demo_charge
    DEFAULT CHARACTER SET utf8mb4;
